### ISSUE TITLE
LGPL License consideration

### ISSUE THREAD

**Issue by jentfoo** [OpenPatternsInc/EntsDatabase#1]
You can obviously license your project any way you want, but since your git commit mentions wanting to allow others to include it in their apps, I thought I would point one thing out.

My project also used to be licensed under LGPL:
https://github.com/threadly/threadly

We ended up switching to Mozilla public license 2.0

The reason being is that LGPL requires you to be able to easily replace the LGPL component.  In the java world this is often interpreted as not being able to create fat jars with LGPL dependencies included.  And it certainly can't be embed as a dependency in projects like Avian: https://github.com/readytalk/avian

MPL 2.0 does not have this static linking requirement, but otherwise is very similar to LGPL.

Again, feel free to ignore, otherwise I like LGPL lots, but thought I would at least point out that little gotcha.

**Comment by jstock23** [comment]
Hey, thanks for your input, I appreciate. I didn't know the fact that JARS bring up problems at least for Java.

I really am thinking about this a lot. On the one hand, I'd like to make it as open as possible to respect user rights because I believe it is extremely important. I also believe it is quite simple, as far as software projects go, so people will just implement proprietary versions of it anyways. By having the original and main version LGPL I think it would allow Free Software the best access to the best version.

I don't want GPL programs to not be able to use it.

On the other hand, I do think it will be quite useful in a variety of contexts, despite it being simple, so I certainly want to accommodate other licenses.

For now it will be LGPL, just because that seems to be more open. Perhaps I'll consider changing the license later if that makes sense, but I'm sticking with LGPL until I understand things better just for safety.

Thanks a lot.
